taptap/tds-docs

docs/sdk/16-engine/02-deploy/01-getting-started.md
docs/sdk/16-engine/02-deploy/02-platform.md
docs/sdk/16-engine/02-deploy/06-java.md
docs/sdk/16-engine/03-functions/01-getting-started.md
docs/sdk/16-engine/_partials/leandb-cli-access.mdx
docs/sdk/16-engine/_partials/quick-start-deploy.mdx
docs/sdk/16-engine/_partials/quick-start-init.mdx
versioned_docs/version-v2/sdk/09-engine/02-guide/12-faq.md

- 代码块样式
- `.leanignore` 的 typo
- 简化快速开始里部署的描述
看完直接合就行。

🩹 Minor fixes for Cloud Engine

---

docs/sdk/11-lisence/02-guide.md

根据内部文档+问人，改了文档：
- SDK 获取，增加 Android 部分（之前只有 Unity）
- 目前「测试」一节，写得过于简单，大部分正版验证工单都是因为游戏测试时无法确定正常的流程是什么。改得比较多。而且这是一个有顺序的流程，加了序号，降级为四级标题，避免右边栏排版不好看。
- 另外就是一些措辞和标点符号。

refactor: improve license guide

---

docs/sdk/start/quickstart.md

项目配置的 unity 部分对 iOS 配置权限没讲清楚，其实只有内嵌动态和数据分析需要某些权限，不使用这两个服务就不需要配置，所以增加说明。

chore: more details on setting iOS app permissions

---

docs/sdk/push/guide/android-mixpush.md

delete unnecessary permissions

---

docs/sdk/start/quickstart.mdx

文档中对 Unity 初始化代码缺失一个命名空间的声明，因此添加上。

增加 Unity 初始化代码相关的命名空间

---

docs/sdk/anti-addiction/guide.mdx
docs/sdk/start/quickstart.mdx
docs/sdk/taptap-login/guide/tap-login.mdx
i18n/en/docusaurus-plugin-content-docs/current/sdk/start/quickstart.mdx
i18n/en/docusaurus-plugin-content-docs/current/sdk/taptap-login/guide/tap-login.mdx
src/docComponents/sdkVersions.ts

Reverts taptap/tds-docs#120
因为 SDK 3.7.1 暂未发布而产品那边需要发布另外一些文档，故暂时回退 #120 ，待 SDK 3.7.1 正式发布后再加回来。

Revert "feat: TapSDK 3.7.1"

---

docs/sdk/start/quickstart.mdx
docs/sdk/taptap-login/guide/start.mdx

简单改改。
- 初始化部分，仅 unity 的示例里写了哪几个是必须填写的参数，补一下 Android 和 iOS 部分，并在下方的文字里再强调一遍。看工单还是有用户认为 sever_url 不是必须的。
- 内建账户下的登录，加一下 sdk 初始化。我们预期的阅读顺序是先读 快速开始 然后再看 登录，但也有可能只想接登录的开发者直接看了这一篇，这种情况，内建账户下的 TapTap 登录就缺少了项目配置和初始化部分。

fix(login): minor improvements

---

src/docComponents/sdkVersions.ts

- TapSDK -> v3.9.0
顺手把其他 SDK 也更新到最新版了。
- objc: https://github.com/leancloud/objc-sdk/releases/tag/13.9.0
- js storage: https://github.com/leancloud/javascript-sdk/releases/tag/v4.12.2
- java: https://github.com/leancloud/java-unified-sdk/releases/tag/leancloud-sdk-8.2.9
- csharp: https://github.com/leancloud/csharp-sdk/pull/215

chore: sdk version bump

---

docs/tap-download.mdx

考虑部分开发者 GitHub 网站服务器无法快速加载 SDK 的问题，因此提供国内网络环境 SDK 镜像下载：

SDK 下载渠道添加国内镜像下载

---

docs/sdk/anti-addiction/guide.mdx
src/docComponents/sdkVersions.ts

相关背景：
- [slack](https://xindong.slack.com/archives/C01HZ8BS7PT/p1663035437028809)
- [confluence](https://xindong.atlassian.net/wiki/spaces/TDS/pages/325327424/SDK+API)
<s>有一些问题：
1. **启用时长限制功能**是不是从配置去掉了，相关内容要一并删掉吗，包括初始化及参数说明（已删除）、上报游戏时长（提到了时长限制）、[faq](http://localhost:3888/docs/sdk/anti-addiction/guide/#%E9%92%88%E5%AF%B9%E6%9C%AA%E6%88%90%E5%B9%B4%E7%94%A8%E6%88%B7%E5%BC%80%E5%90%AF%E6%97%B6%E9%95%BF%E9%99%90%E5%88%B6%E5%8A%9F%E8%83%BD)；另外上报游戏时长这看上去是保留了，那么和启用时长限制功能这个配置无关了吗？
2. 获取年龄这个和目前的[获取玩家年龄段](https://developer.taptap.com/docs/sdk/anti-addiction/guide/#%E8%8E%B7%E5%8F%96%E7%8E%A9%E5%AE%B6%E5%B9%B4%E9%BE%84%E6%AE%B5)是不一样的，要替换吗，unity 和 ios 也要换吗（尚未提供）？
3. 获取用户剩余时长、获取用户剩余时长这两个之前文档没有，要加吗（感觉对国内防沉迷没什么用处，同样另两个 sdk 尚未提供）
4. enterGame、leaveGame、查询能否支付、上报消费结果这四个看上去和已有的没区别，但列到 conf 里面了，不确定要做什么。 …

chore(anti-addiction): 3.15.0 native sdk

---

docs/sdk/storage/js-guide/setup-js.mdx

JS 即时通讯 SDK 的富媒体消息插件之前改过，初始化方式变成 `initPlugin(AV, IM)` 了。没想到落下了一部分没改，这里给改过来。

fix(lc): init js realtime sdk with typed message

---

docs/sdk/start/faq.mdx

- 增加 iOS TapTap 登录报 accessToken: sdk_not_matched 异常的解决方案。

docs: add faq

---

docs/tap-download.mdx
i18n/en/docusaurus-plugin-content-docs/current/tap-download.mdx

docs: Remove outdated TapSDKSuite

---

docs/sdk/_partials/languages.mdx
i18n/en/docusaurus-plugin-content-docs/current/sdk/_partials/languages.mdx

ue 添加多语言类型：
- 德语
- 西班牙语
- 法语
- 葡萄牙语
- 俄语
- 土耳其语
- 越南语

ue 添加多语言类型

---

docs/sdk/taptap-login/guide/taptap-oauth.mdx
i18n/en/docusaurus-plugin-content-docs/current/sdk/taptap-login/guide/taptap-oauth.mdx

https://xindong.slack.com/archives/C01S9A1B4GK/p1698895159125479
这两个字段目前用户中心是等效的，短期内也没有计划用谁取代谁, 先改为一样的

docs: change the preference of the fields "access_token" and "kid" 

---

i18n/en/docusaurus-plugin-content-docs/current/sdk/tap-support/features.md

翻译的是这一篇 https://developer.taptap.cn/docs/sdk/tap-support/features/

add i18n for support

---

docs/sdk/engine/_partials/nodejs-setup-dependencies.mdx
docs/sdk/engine/_partials/nodejs-setup-package-mamager.mdx
docs/sdk/engine/deploy/nodejs.mdx
docs/sdk/engine/deploy/webapp.mdx
i18n/en/docusaurus-plugin-content-docs/current/sdk/engine/_partials/nodejs-setup-dependencies.mdx
i18n/en/docusaurus-plugin-content-docs/current/sdk/engine/_partials/nodejs-setup-package-manager.mdx
i18n/en/docusaurus-plugin-content-docs/current/sdk/engine/deploy/nodejs.mdx
i18n/en/docusaurus-plugin-content-docs/current/sdk/engine/deploy/webapp.mdx

云引擎给 Node.js 运行时添加了 Corepack 支持，修改文档

feat(nodejs): add docs for cloud engine corepack support

---

docs/sdk/copyright-verification/guide.mdx

- 正版验证将「付费下载」和「DLC」由一级目录更改成二级目录，方便锚定快速定位。

docs:Change of primary to secondary headings

---

docs/shadow/tap-update-old-guide.mdx

- 将早期的更新唤起文档进行隐藏，避免 AI 客服团队读取进行训练

docs: move old update to shadow

---

versioned_docs/version-v4/sdk/access/get-ready.mdx
versioned_docs/version-v4/sdk/access/quickstart.mdx
versioned_docs/version-v4/sdk/achievement/features.mdx
versioned_docs/version-v4/sdk/taptap-login/_category_.json
versioned_docs/version-v4/sdk/update/_category_.json

- 「DC 控制台配置」，适合改名为「开发者中心配置」
- 修复成就图片展示异常
- 排序上：「TapTap 登录」移动至「更新唤起」之上

docs: optimise documentation details

---

docs/sdk/taptap-login/faq.mdx
docs/tap-download.mdx

- 修复 V4 Unity SDK 下载链接
- 去除 V4 Login 模块 FAQ 中过时的描述

docs: fix unity sdk download links & del outdate faq

---

cn/docs/sdk/taptap-login/guide.mdx

docs: formatting

---

cn/docs/sdk/access/quickstart.mdx

docs:code amendment

---

cn/docs/sdk/taptap-login/best-practice.mdx
hk/docs/sdk/taptap-login/best-practice.mdx
hk/i18n/en/docusaurus-plugin-content-docs/current/sdk/taptap-login/best-practice.mdx

docs: remove obsolete descriptions for taplogin checkoutlist module

---

cn/docs/sdk/taptap-login/taptap-oauth.mdx
cn/versioned_docs/version-v3/sdk/taptap-login/guide/taptap-oauth.mdx
hk/docs/sdk/taptap-login/taptap-oauth.mdx
hk/i18n/en/docusaurus-plugin-content-docs/current/sdk/taptap-login/taptap-oauth.mdx
hk/i18n/en/docusaurus-plugin-content-docs/version-v3/sdk/taptap-login/guide/taptap-oauth.mdx
hk/versioned_docs/version-v3/sdk/taptap-login/guide/taptap-oauth.mdx

- 增加针对调用 TapTap OAuth 接口返回  insufficient_scope 异常的说明。

docs: Add a description of the insufficient_scope returned by callso the OAuth Interface.

---

cn/docs/sdk/apk-upload/guide.mdx

docs: Shell signing example for writing an interface for uploading APKs
