taptap/tds-docs

src/pages/_config.ts
=> fix: show community guide card in cn

docs/community/features.md, docs/sdk/15-storage/02-guide/02-dotnet.md, docs/sdk/15-storage/02-guide/04-java.md, docs/sdk/15-storage/02-guide/06-objc.md, docs/tap-download.md, i18n/eng/docusaurus-plugin-content-docs/current/tap-download.md, versioned_docs/version-v2/sdk/04-embedded-moments/01-features.md, versioned_docs/version-v2/sdk/08-storage/02-guide/02-dotnet.md, versioned_docs/version-v2/sdk/08-storage/02-guide/04-java.md, versioned_docs/version-v2/sdk/08-storage/02-guide/06-objc.md, versioned_docs/version-v2/tap-download.md
lncld.net is clientHold now
slack:
https://xindong.slack.com/archives/C02TXPV4UKW/p1643280971034000
=> fix: replace lncld.net with lcfile.com

src/docComponents/sdkVersions.ts
=> feat: LC Java sdk version bump to 8.2.4

docs/sdk/10-anti-addiction/02-guide.md
Thank zhaopenghui for bringing this to our attention.
=> feat: anti-addiction auth token do not expire

docs/sdk/01-start/04-quickstart.md, docs/sdk/10-anti-addiction/02-guide.md, versioned_docs/version-v2/sdk/01-start/04-quickstart.md
见 [slack](https://xindong.slack.com/archives/C01EN4GRJQP/p1642505477153100)。
=> fix: specify android version requirements

docs/sdk/01-start/04-quickstart.md, docs/sdk/02-taptap-login/01-features.md, docs/sdk/02-taptap-login/02-guide/00-start.md, docs/sdk/02-taptap-login/02-guide/01-tap-login.md, docs/sdk/02-taptap-login/03-best-practice.md, docs/sdk/10-anti-addiction/02-guide.md, docs/tap-support.md, versioned_docs/version-v2/sdk/02-taptap-login/01-features.md
1、Webview 参照 Google 官方文档将首字母 w 更正为大写；
2、防沉迷授权更改成防沉迷认证；
=> Webview 防沉迷认证描述更正

docs/sdk/02-taptap-login/02-guide/00-start.md, docs/sdk/10-anti-addiction/02-guide.md
=> add login and anti blog

docs/sdk/02-taptap-login/02-guide/00-start.md
1、去除多余的 :::
2、tip 更改成 info，更为美观
=> fix: remove extra ::: 

src/docComponents/sdkVersions.ts
https://github.com/leancloud/csharp-sdk/pull/196
=> feat: C# SDK version bump 0.10.2

docs/sdk/gamesaves/guide.md
=> fix: gamesave delete should not block

src/docComponents/sdkVersions.ts
https://github.com/leancloud/csharp-sdk/pull/203
=> feat: C# SDK version bump 0.10.5

docs/sdk/start/quickstart.mdx
=> 提供获取签名 MD5 值工具

docs/sdk/storage/java-guide/java.mdx
Thank [vrtriber] for bringing this to our attention.
[vrtriber]: https://forum.leancloud.cn/t/android-sdk/25079
=> java: return value of LCFile save with progress

src/docComponents/sdkVersions.ts
https://github.com/leancloud/csharp-sdk/pull/207
=> feat: C# SDK version bump 0.10.7

docs/sdk/anti-addiction/guide.mdx, docs/sdk/start/quickstart.mdx, docs/sdk/taptap-login/guide/tap-login.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/start/quickstart.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/taptap-login/guide/tap-login.mdx, src/docComponents/sdkVersions.ts, versioned_docs/version-v2/sdk/01-start/04-quickstart.mdx
1、optimize ios url intercept.
2、antiaddiction add new function: authorize realname info from taptap
=> feat: TapSDK 3.7.1

docs/sdk/anti-addiction/guide.mdx, docs/sdk/start/quickstart.mdx, docs/sdk/taptap-login/guide/tap-login.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/start/quickstart.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/taptap-login/guide/tap-login.mdx, src/docComponents/sdkVersions.ts
=> Revert "Revert "feat: TapSDK 3.7.1""

docs/sdk/gamesaves/guide.mdx
内部讨论：https://xindong.slack.com/archives/C01UL3RMUBX/p1647835780287229
=> fix(gamesaves): remove `user` and `ACL` from request body

docs/sdk/taptap-login/guide/tap-login.mdx
之前 https://github.com/taptap/tds-docs/pull/129 没改全，补一下。
=> fix(unity): Common now depends on Storage

docs/sdk/anti-addiction/guide.mdx
鉴于实名认证防尘迷，不少开发者搞不清楚注册监听回调和调用认证接口触发回调的问题做了简单说明。
=> 优化初始化和认证接口的关系说明

docs/sdk/taptap-login/guide/start.mdx
主要是想把登录后可以拿到的信息写详细点，比如工单有开发者问过的 [openid 会包含哪些字符](https://dc.leanticket.cn/tickets/10565)。
顺便改了标题和措辞。（之前有一些标题太长了）
=> feat: taptap login profile with more details

docs/sdk/friends/mutual.mdx, src/docComponents/sdkVersions.ts
见 [slack](https://xindong.slack.com/archives/C02BDEY38N4/p1652338146531699)
=> feat(friends): TapSDK 3.8

docs/sdk/tapdb/sdk/client-side-integration.mdx
https://dc.leanticket.cn/tickets/11050
=> fix: tapdb unity dependency

docs/sdk/achievement/guide.mdx, docs/sdk/anti-addiction/guide.mdx, docs/sdk/copyright-verification/guide.mdx, docs/sdk/dlc/guide.mdx, docs/sdk/embedded-moments/guide.mdx, docs/sdk/friends/guide.mdx, docs/sdk/rtc/guide.mdx, docs/sdk/start/quickstart.mdx, docs/sdk/tapdb/sdk/client-side-integration.mdx, docs/sdk/taptap-login/guide/tap-login.mdx, docs/sdk/update/guide.mdx, docs/tap-download.mdx, docs/tap-support.mdx
见 [slack](https://xindong.slack.com/archives/C01HZ8BS7PT/p1652439287737479?thread_ts=1651210994.483669&cid=C01HZ8BS7PT)
=> fix: sdk download

docs/sdk/anti-addiction/guide.mdx
改 https://github.com/taptap/tds-docs/pull/128 的时候写错了。
上下文见 [slack](https://xindong.slack.com/archives/C01S9A1B4GK/p1653026299606939?thread_ts=1649845066.550869&cid=C01S9A1B4GK)。
=> fix(anti-addiction): typo

docs/sdk/_partials/android-package-visibility.mdx
工单和 Slack 上心动游戏反馈不知道如何添加 queries 标签的位置进行说明
=> queries 标签的位置进行说明

docs/sdk/anti-addiction/guide.mdx
=> 防沉迷 Unity 添加 UPM 方式集成

docs/sdk/friends/guide.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/friends/guide.mdx
Thank [hechang] for bringing this to our attention.
[hechang]: https://xindong.slack.com/archives/C02BDEY38N4/p1643271842145100?thread_ts=1643268272.144900&cid=C02BDEY38N4
=> fix: rich presence rest api typo

docs/sdk/engine/functions/rest-api.mdx
Thank [qiuyi] for bringing this to our attention.
[qiuyi]: https://xindong.slack.com/archives/C01S89MAHTL/p1645177012723689
=> fix: cloud function rest api request schema

docs/sdk/anti-addiction/guide.mdx
TapAntiAddiction for iOS 部分如果没有接 TapLogin 需要补充一下 URLSchema 的配置
=> fix: 实名认证 iOS 补充 URLSchema 的配置

docs/sdk/anti-addiction/guide.mdx
https://dc.leanticket.cn/tickets/12502
=> fix(anti-addiction): unity sdk namespace

docs/sdk/push/guide/android-mixpush.mdx
=> fix(mixpush): correctly display sdk version

docs/sdk/leaderboard/guide.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/leaderboard/guide.mdx
https://dc.leanticket.cn/tickets/9653
=> fix(leaderboard): code examples

docs/sdk/gamesaves/guide.mdx
https://dc.leanticket.cn/tickets/9605
=> fix: add description of gameFile.Url

docs/sdk/anti-addiction/guide.mdx, docs/sdk/copyright-verification/guide.mdx, docs/sdk/dlc/guide.mdx, docs/sdk/embedded-moments/guide.mdx, docs/sdk/start/quickstart.mdx, docs/sdk/update/guide.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/copyright-verification/guide.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/dlc/guide.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/embedded-moments/guide.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/update/guide.mdx, versioned_docs/version-v2/sdk/01-start/04-quickstart.mdx
https://dc.support.tdspowered.com/tickets/57
一些单独接入的功能漏掉了，补上。
同步改了英文版。
=> fix(unity): Common depends on Storage

i18n/en/docusaurus-plugin-content-docs/current/design/design-billboard.mdx
https://github.com/taptap/tds-docs/pull/206#discussion_r927312084
=> Correct the English translation

docs/sdk/billboard/guide.mdx, src/docComponents/sdkVersions.ts
=> Fix billboard

docs/sdk/domain/icp.mdx
https://xindong.slack.com/archives/C03SNTT9C7Q/p1660057495321489?thread_ts=1660057122.980879&cid=C03SNTT9C7Q
=> chore(billboard): icp

docs/sdk/start/quickstart.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/start/quickstart.mdx
https://xindong.slack.com/archives/C03SNTT9C7Q/p1660057971198559
=> fix: init sdk on android main thread

docs/sdk/storage/dotnet-guide/setup-dotnet.mdx, docs/sdk/storage/java-guide/setup-java.mdx, docs/sdk/storage/objc-guide/setup-objc.mdx
https://dc.leanticket.cn/tickets/16462
=> fix: avoid duplicate intialization

docs/sdk/billboard/guide.mdx
https://xindong.slack.com/archives/C03HJFMQ65B/p1662455389808669
=> fix(billboard): use default platform params

docs/sdk/anti-addiction/guide.mdx
=> chore: update anti addiction unity doc

docs/sdk/leaderboard/guide.mdx
=>  TapSDK 3.10.0 新增排行榜接口

i18n/en/docusaurus-plugin-content-docs/current/sdk/dlc/features.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/start/quickstart.mdx
同步修改英文文档：
https://github.com/taptap/tds-docs/pull/265
https://github.com/taptap/tds-docs/pull/270
=> chore(i18n)：PR 265 and 270

docs/sdk/start/quickstart.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/start/quickstart.mdx
https://xindong.slack.com/archives/C01HZ8BS7PT/p1663814390037459
=> fix(quickstart): remove outdated unity config info

docs/sdk/gamesaves/guide.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/gamesaves/guide.mdx
https://dc.leanticket.cn/tickets/18348
=> fix(gamesave): typo

docs/sdk/multiplayer/guide/cs.mdx
[slack](https://xindong.slack.com/archives/C01S9A1B4GK/p1664116317758109)
=> fix(multiplayer):typo

docs/sdk/anti-addiction/guide.mdx
SDK 和文档同步发，有些细节就没验证了。流泪。
下次考虑等 SDK 发完我们验证一遍再发文档。
https://dc.leanticket.cn/tickets/18644
=> fix(anti-addiction): unity package naming

docs/sdk/taptap-login/guide/start.mdx
https://xindong.slack.com/archives/C01E0BLSKUG/p1664246177438749
=> fix(login): email scope for global only

docs/sdk/leaderboard/guide.mdx
=> 更正「获取排行榜属性」接口

docs/sdk/anti-addiction/guide.mdx
https://xindong.slack.com/archives/C01EN4GRJQP/p1667301471256679
=> chore: emphasize anti-addiction api token

docs/sdk/multiplayer/guide/cs.mdx, docs/sdk/multiplayer/guide/js.mdx
[讨论](https://xindong.slack.com/archives/C01S8E7PVC3/p1667897473200129)
=> fix: play kick event

docs/sdk/authentication/guide.mdx
[Slack](https://xindong.slack.com/archives/C01HZ8BS7PT/p1668424162512019?thread_ts=1668423240.870849&cid=C01HZ8BS7PT)
=> fix(user): update return type of user association

docs/sdk/copyright-verification/guide.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/copyright-verification/guide.mdx
等用户确认之后再合并。
https://xindong.slack.com/archives/C01EB1KAE4B/p1668484598220999
=> fix(paid-games): minimum charge amount

docs/sdk/start/faq.mdx
- 增加 {"code":36869,"error_description":"Unauthorized."}  异常说明
- 工单：https://dc.leanticket.cn/tickets/20699
- 工单：https://dc.leanticket.cn/tickets/19858
=> 增加登录失败的 FAQ 说明

docs/tds-tapad.mdx
=> feat:update params

docs/sdk/multiplayer/features.mdx, docs/sdk/multiplayer/guide/cs.mdx, docs/sdk/multiplayer/guide/js.mdx, docs/sdk/multiplayer/start/cs.mdx, docs/sdk/multiplayer/start/js.mdx, src/docComponents/MultiLang/index.tsx
https://dc.leanticket.cn/tickets/12430
=> fix(multiplayer): client init parameters

docs/sdk/anti-addiction/guide.mdx
- 用户唯一标识参数增加长度限定说明 [工单](https://dc.leanticket.cn/tickets/22698)、[Slack](https://xindong.slack.com/archives/C01S8G6QV8S/p1670934742546429)
=> 用户唯一标识参数增加长度限定说明

docs/tds-payment.mdx
[Slack](https://xindong.slack.com/archives/C01S9A1B4GK/p1671011492356159)
=> update payment webhook

docs/sdk/update/guide.mdx
https://dc.leanticket.cn/tickets/21544
https://dc.leanticket.cn/tickets/18812
=> chore(update): improve wording

docs/sdk/tds-gift/guide.mdx
- 礼包系统增加无服务器兑换接口请求示例。工单：https://dc.leanticket.cn/tickets/23228
=> 增加无服务器兑换接口请求示例

.ci/leancloud/zh-Hans/sdk/storage/friendship.md
LC 文档
- 新增了 [好友关系开发指南](https://leancloud.cn/docs/leanstorage_friendship_guide.html)
- 由于 TDS 的好友已经是另外一套，所以这篇文档之后不会出现在 TDS 中，不需要处理品牌差异
- 修正了内链和多语言排版
=> feat(lc): friendship

.ci/build-leancloud.sh, .ci/leancloud/zh-Hans/sdk/error-code.mdx
LC 文档
- 新增 [错误码详解](https://leancloud.cn/docs/error_code.html)
- 这篇文档暂时不放 TDS，未处理品牌差异（其实差异不大）
- 修正了内链和排版
=> feat(lc): error code

docs/tds-payment.mdx
[工单](https://dc.leanticket.cn/tickets/24750)
=> chore(payment): update webhook description

.ci/leancloud/zh-Hans/sdk/storage/best-practice/custom-reset-verify-page.mdx, .ci/leancloud/zh-Hans/sdk/storage/java-guide/setup-android-securely.mdx
新增
存储下面的《自定义邮件验证和重设密码页面》和《Android SDK 更安全的接入和初始化方式》
=> feat(lc): best practice

docs/sdk/push/guide/android-mixpush.mdx
[Slack](https://xindong.slack.com/archives/C01HZ8BS7PT/p1675249032127859?thread_ts=1675247629.618549&cid=C01HZ8BS7PT)
=> chore(push): remove unnecessary permission

docs/sdk/anti-addiction/guide.mdx
=> [fix] fix unity anti addiction description bug

.github/workflows/preview-env-delete.yml, .github/workflows/preview-env-deploy.yml
Use LeanEngine's deploy preview feature!
see also https://github.com/taptap/tds-docs/pull/404
=> Add workflow files for preview environments

src/docComponents/sdkVersions.ts
=> doc: update sdk version

docs/sdk/im/guide/beginner.mdx, docs/sdk/im/guide/rest.mdx, docs/sdk/push/guide/rest.mdx
关联[工单](https://www.leanticket.cn/tickets/40606)
=> chore(rtm): Add explanation for "lm"

docs/sdk/taptap-login/guide/start.mdx
=> fix: correct wrong words

docs/tds-tapad.mdx
=> fix:tag format

docs/sdk/push/guide/android.mdx
关联[工单](https://dc.leanticket.cn/tickets/29735)
预览效果：
=> chore: update android push notification

docs/sdk/im/guide/intermediate.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/im/guide/intermediate.mdx, versioned_docs/version-v2/sdk/10-im/02-guide/02-intermediate.mdx
去掉过时的 inherit，改为使用 extends 语法。
=> docs(im): prefer extends syntax

.ci/leancloud/docusaurus.config.js
=> feat: js realtime sdk api doc

i18n/en/docusaurus-plugin-content-docs/current/sdk/achievement/features.mdx
=> docs: update outdated pics for achievement module

i18n/en/docusaurus-plugin-content-docs/current/sdk/achievement/features.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/billboard/features.mdx
=> docs: update outdated pics for billboard module

i18n/en/docusaurus-plugin-content-docs/current/sdk/achievement/features.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/billboard/features.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/leaderboard/guide.mdx
=> docs: update outdated pic for leaderboard module

docs/sdk/anti-addiction/guide.mdx
- 增加实名认证防沉迷 Unity 导出 Xcode 配置详情说明。
=> docs: Anti for Unity to Xcode

docs/tds-tappay-commodity-management.mdx
=> fix: bad link

i18n/en/docusaurus-plugin-content-docs/current/sdk/tds-gift/features.mdx
=> docs: update outdated pics for git module

docs/sdk/taplink/features.mdx
- 增加对 scheme 的说明
- 更换张 scheme 具有大写字母的控制台图片
- 增加安卓包体配置 scheme 示例
=> docs: add description of scheme configuration

docs/sdk/friends/follow.mdx, docs/sdk/friends/mutual.mdx
=> fix: correcting error code

docs/sdk/achievement/guide.mdx, docs/sdk/anti-addiction/guide.mdx, docs/sdk/authentication/guide.mdx, docs/sdk/billboard/guide.mdx, docs/sdk/embedded-moments/guide.mdx, docs/sdk/friends/guide.mdx, docs/sdk/leaderboard/guide.mdx, docs/sdk/start/quickstart.mdx, docs/sdk/tap-friend/guide.mdx, docs/sdk/tapdb/sdk/client-side-integration.mdx, docs/sdk/taptap-login/guide/start.mdx, docs/sdk/taptap-login/guide/tap-login.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/start/quickstart.mdx, versioned_docs/version-v2/sdk/01-start/04-quickstart.mdx
- iOS 增加 Xcode 版本需求说明。[工单](https://dc.leanticket.cn/tickets/32409)
=> docs: add Xcode version statement

docs/sdk/TapPayments/features/tds-tappay-commodity-management.mdx, docs/sdk/TapPayments/features/tds-tappay-introduce.mdx, docs/sdk/TapPayments/features/tds-tappay-orders-refunds.mdx, docs/sdk/achievement/guide.mdx, docs/sdk/anti-addiction/guide.mdx, docs/sdk/authentication/guide.mdx, docs/sdk/billboard/guide.mdx, docs/sdk/embedded-moments/guide.mdx, docs/sdk/friends/guide.mdx, docs/sdk/leaderboard/guide.mdx, docs/sdk/start/quickstart.mdx, docs/sdk/tap-friend/guide.mdx, docs/sdk/tapdb/sdk/client-side-integration.mdx, docs/sdk/taptap-login/guide/start.mdx, docs/sdk/taptap-login/guide/tap-login.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/anti-addiction/guide.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/billboard/guide.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/push/guide/ios.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/start/quickstart.mdx, versioned_docs/version-v2/sdk/01-start/04-quickstart.mdx
- io 部分关于 iOS 增加 Xcode 版本要求说明
- 更改 TapPayments 展示图片
=> docs: change tappayment pic & add xcode version statement for io

docs/sdk/TapPayments/features/tds-tappay-commodity-management.mdx, docs/sdk/TapPayments/features/tds-tappay-introduce.mdx, docs/sdk/TapPayments/features/tds-tappay-orders-refunds.mdx, docs/sdk/TapPayments/tds-payments-global.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/anti-addiction/guide.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/billboard/guide.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/push/guide/ios.mdx
=> docs: update details

i18n/en/docusaurus-plugin-content-docs/current/sdk/TapPayments/Global/_category_.json, i18n/en/docusaurus-plugin-content-docs/current/sdk/TapPayments/Global/features/tds-tappay-commodity-management.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/TapPayments/Global/features/tds-tappay-introduce.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/TapPayments/Global/features/tds-tappay-orders-refunds.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/TapPayments/Global/tds-tappay-product-description.mdx, src/docComponents/sdkVersions.ts
=> docs: update TapPayments for io

src/docComponents/sdkVersions.ts
=> docs: update sdk version

docs/demos.mdx
=> add UE and Unity Demo

docs/sdk/achievement/features.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/achievement/features.mdx
=> docs: update presentation of achievements on TapTap

docs/sdk/achievement/guide.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/achievement/guide.mdx
- 更正错误的成就 REST API 接口参数以及优化部分参数说明。
=> docs: update args for achievement REST API

.ci/hk/en/sdk/TapPayments/Global/tds-tappay-product-description.mdx, .ci/hk/zh-Hans/sdk/TapPayments/Global/tds-tappay-product-description.mdx
=> docs: update taypayments add guide

docs/tds-payment.mdx
- 增加国内 TapPayment 关于 Android 原生接入说明。
=> docs:update TapPayment for CN Android

docs/tds-payment.mdx, src/theme/MDXContent/index.tsx
=> fix:login status for doc feedback"

.ci/hk/en/sdk/TapPayments/Global/tds-payments-global.mdx, .ci/hk/zh-Hans/sdk/TapPayments/Global/tds-payments-global.mdx
=> fix:Removing excess in sample code for tappayments

docs/sdk/anti-addiction/features.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/anti-addiction/features.mdx
=> docs: 优化中宣部后台注册流程

docs/sdk/anti-addiction/guide.mdx
add antiAddiction's tip about condition whether user can enter
=> add antiAddiction tip about conditio

docs/sdk/tapdb/sdk/client-side-integration.mdx, docs/tap-download.mdx
修改了themis upm的集成url,增加了themis 的资源下载链接
=> 修改了themis upm的集成url,增加了themis 的资源下载链接

.ci/hk/zh-Hans/sdk/TapPayments/Global/tds-payments-global.mdx
=> feat: update global-payment api

i18n/en/docusaurus-plugin-content-docs/current/sdk/copyright-verification/guide.mdx
=> docs:Chinese-English synchronisation for copyright module

src/theme/Footer/TdsFooter/index.tsx, src/theme/Footer/TdsFooter/lib/ssr/footer.js
=> feat: update discord link

docs/sdk/taptap-connect/guide.mdx
添加关于悬浮窗单独初始化的时候，如何初始化 TapLogin 和 TapMoment 的说明
=> update: add TapTap Connect init description

docs/design/design-login.mdx
- 根据 #dc-document-feedback 用户的反馈，更正错别字。
=> docs:Correcting typographical errors

docs/design/design-login.mdx, docs/store/long-termops/long-term.mdx
- 更正失效链接，[Slack](https://xindong.slack.com/archives/C01EN4GRJQP/p1696667232301079)。
=> fix: fix bad link

docs/design/design-billboard.mdx
URL: https://developer.taptap.cn/docs/design/design-billboard/
=> fix: Fix incorrect number

docs/store/events/events-handbook.mdx, docs/store/long-termops/long-term.mdx, docs/store/test/test-handbook.mdx
- 修复坏链，[Slack](https://xindong.slack.com/archives/C01EN4GRJQP/p1697438136689569?thread_ts=1696667232.301079&cid=C01EN4GRJQP)。
=> docs:fix bad links

docs/sdk-api.mdx, docusaurus.config.js
=> Update the link to Unity SDK API reference

docs/sdk/update/features.mdx
=> docs:changing the hierarchy for update-features

docs/sdk/dlc/guide.mdx
=> docs:update DLC

docs/sdk/anti-addiction/guide.mdx, docs/tap-update-old-guide.mdx
=> docs:Remove duplicate description

docs/sdk/update/guide.mdx
=> fix:fix bad link

docs/sdk/taptap-appsafety/_category_.json, docs/sdk/taptap-appsafety/features.mdx, docs/sdk/taptap-appsafety/guide.mdx
=> docs: add app safety module

docs/sdk/taptap-login/faq.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/taptap-login/faq.mdx
=> docs: faq for taplogin

docs/sdk/taptap-login/guide/taptap-oauth.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/taptap-login/guide/taptap-oauth.mdx
https://xindong.slack.com/archives/C01S9A1B4GK/p1698637412767999
1. 更新开放平台domain
2. 更改开放平台文档描述
=> docs: update oauth domain #no-ticket

docs/sdk/_partials/unity-sdk-installation.mdx, docs/sdk/achievement/guide.mdx, docs/sdk/anti-addiction/guide.mdx, docs/sdk/authentication/guide.mdx, docs/sdk/billboard/guide.mdx, docs/sdk/copyright-verification/guide.mdx, docs/sdk/dlc/guide.mdx, docs/sdk/embedded-moments/guide.mdx, docs/sdk/friends/guide.mdx, docs/sdk/start/quickstart.mdx, docs/sdk/tap-friend/guide.mdx, docs/sdk/tap-support/guide.mdx, docs/sdk/tapdb/sdk/client-side-integration.mdx, docs/sdk/taptap-connect/guide.mdx, docs/sdk/taptap-login/guide/start.mdx, docs/sdk/update/guide.mdx
- 抽象出 Unity SDK 安装文档，感谢 @fuchenshi 
- 增加 NPM 安装文档
=> 添加 NPM 安装方式介绍

src/docComponents/sdkVersions.ts
=> 升级 Unity SDK 版本

docs/store/operations-skills/event-notice.mdx
=> docs: add event notice

docs/sdk/anti-addiction/faq.mdx
=> docs:faq for anti

docs/sdk/taptap-login/guide/taptap-oauth.mdx
=> fix: correction of incorrect request host

.ci/hk/en/sdk/TapPayments/Global/tds-payments-global.mdx, .ci/hk/zh-Hans/sdk/TapPayments/Global/tds-payments-global.mdx
- TapPayments Global CURL 代码示例代码更正
- Webhooks 关于 API 密钥描述更正
=> docs:Correction of misdescription

.ci/leancloud/docusaurus.config.js
=> feat: add javascript im sdk api link

.ci/hk/en/sdk/TapPayments/Global/tds-tappay-product-description.mdx, .ci/hk/zh-Hans/sdk/TapPayments/Global/tds-tappay-product-description.mdx
=> docs: add a reference

docs/sdk/tap-adn/tds-tapad.mdx
=> 自渲染信息广告注册需传入activity

docs/sdk/engine/functions/guides.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/engine/functions/guides.mdx
[Slack](https://xindong.slack.com/archives/C01S9A1B4GK/p1701142024981459)
=> fix php example code

docs/sdk/anti-addiction/guide.mdx
=> docs: update anti init description

.ci/leancloud/docusaurus.config.js, .ci/leancloud/zh-Hans/sdk/other/error-code.mdx, docs/sdk-api.mdx, docs/sdk/storage/fulltext-search/fulltext-search-guide.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/storage/fulltext-search/fulltext-search-guide.mdx, versioned_docs/version-v2/sdk/08-storage/02-guide/08-fulltext-search.mdx
将 `leancloud.cn/api-docs` 的 URL 更换成对应文档的 GitHub Pages 链接
=> fix: remove leancloud.cn/api-docs url

docs/sdk/anti-addiction/guide.mdx, docs/sdk/authentication/guide.mdx, docs/sdk/rtc/guide.mdx, docs/sdk/start/quickstart.mdx, docs/sdk/tapdb/sdk/client-side-integration.mdx, docs/sdk/taptap-login/guide/start.mdx, docs/sdk/taptap-login/guide/tap-login.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/anti-addiction/guide.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/rtc/guide.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/start/quickstart.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/tapdb/sdk/client-side-integration.mdx, versioned_docs/version-v2/sdk/01-start/04-quickstart.mdx
=> docs: add xcode config

docs/sdk/push/guide/android.mdx, docs/sdk/storage/security.mdx
fix 公用文档修改了 TapTap 显示的是 AppId 和 AppKey ，其实 TapTap 应该显示 ClientID 和ClientToken ，LC 才是 AppID 和 AppKey
=> fix 公用文档修改了 TapTap 显示的是 APPID 和 APPKEY。

docs/tap-adn/adn-compliance.mdx, yarn.lock
=> Revert "下架 TapADN 文档"

docs/sdk/achievement/guide.mdx, docs/sdk/billboard/guide.mdx, docs/sdk/domain/guide.mdx, docs/sdk/leaderboard/guide.mdx, docs/sdk/taptap-login/guide/start.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/achievement/guide.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/billboard/guide.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/leaderboard/guide.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/taptap-login/guide/start.mdx
防沉迷视频教程暂时不更新到文档了，视频录制的时候仍是旧版防沉迷，以免误导用户。
=> Add video tutorial address

docs/sdk/push/guide/android-mixpush.mdx
please wait for sdk releasing.
refers: https://github.com/leancloud/java-unified-sdk/pulls#240 [240-245]
=> upgrade mixpush SDKs

docs/sdk/anti-addiction/guide.mdx
=> docs: Correcting the parameters of the initialisation interface 

docs/sdk/taptap-login/faq.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/taptap-login/faq.mdx
- 更加 TapTap 登录报 application id is empty 排查方法。
=> docs: add faq for application id is empty exception

docs/sdk/update/faq.mdx, docs/sdk/update/guide.mdx
=> docs: update open comment api

docs/sdk/im/guide/intermediate.mdx, docs/sdk/storage/faq.mdx, docs/shadow/push/guide/Unreal.mdx, docs/shadow/push/guide/android-mixpush.mdx, docs/shadow/push/guide/android.mdx, docs/shadow/push/guide/ios.mdx, docs/shadow/push/guide/overview.mdx, docs/shadow/push/guide/push-faq.mdx, docs/shadow/push/guide/rest.mdx, docs/shadow/push/guide/unity.mdx
=> Revert "修改push 链接"

docs/sdk/update/features.mdx
=> docs: update optimisation of details

docs/sdk/update/faq.mdx
=> faq:Unable to get provider com.taptap.services.update.TapUpdateFileProvider

docs/sdk/tap-play/features.mdx
=> docs:update tappaly feature

.ci/leancloud/zh-Hans/sdk/storage/java-guide/sdk-introduction.mdx
=> fix: a slug conflict

docs/sdk/start/overview.mdx
=> fix: error

docs/sdk/start/compliance.mdx, docs/sdk/start/overview.mdx
=> docs: change a word

docs/sdk/anti-addiction/guide.mdx, docs/sdk/copyright-verification/guide.mdx, docs/sdk/dlc/guide.mdx, docs/sdk/embedded-moments/guide.mdx, docs/sdk/leaderboard/guide.mdx, docs/sdk/update/guide.mdx
=> docs: formatting

docs/shadow/push/guide/android-mixpush.mdx
=> lc: add description for push test

docs/sdk/tap-adn/tds-tapad.mdx
自渲染信息流广告接口变更:
1. 增加视频回调接口
2. 增加视频控制接口
=> 自渲染信息流广告接口变更

.ci/hk/en/sdk/TapPayments/develop/server.mdx, .ci/hk/zh-Hans/sdk/TapPayments/develop/server.mdx
=> feat: update sdk payment server mdx

.ci/hk/zh-Hans/store/store-admin.mdx
=> docs: store admin

.ci/hk/zh-Hans/store/store-admin.mdx
=> docs:optimised pictures

docs/shadow/features.mdx
=> docs:temporary shelter store/game_account/features

docs/store/game_account/features.mdx
=> Revert "docs:temporary shelter store/game_account/features"

docs/tap-download.mdx
=> sdk 下载域名替换

docs/sdk/copyright-verification/guide.mdx, docs/sdk/dlc/guide.mdx
=> Revert "feat: 新增正版验证&DLC模块内测开发文档"

.ci/hk/en/sdk/TapPayments/develop/server.mdx, .ci/hk/zh-Hans/sdk/TapPayments/develop/server.mdx, src/docComponents/MultiLang/index.tsx
=> docs: update sdk payment server mdx

docs/sdk/anti-addiction/guide.mdx, docs/sdk/taptap-login/guide/start.mdx
- 更正下 TapTap 登录和合规认证初始化方式的推荐使用方式
=> docs:update priority

docs/sdk/anti-addiction/guide.mdx
- 更正合规认证 Unity 插件关于 SDK 初始化代码。
=> fix: update anti init code for unity

docs/sdk/copyright-verification/guide.mdx, docs/tap-download.mdx, versioned_docs/version-v2/tap-download.mdx
- 去除 Oaid 下载链接，[Slack](https://xindong.slack.com/archives/C06Q75TQLLT/p1716785808547149)；
=> docs: delete oaid sdk download link

docs/sdk/anti-addiction/guide.mdx
docs: remove realname blog #no-ticket
=> docs: remove realname blog #no-ticket

docs/sdk/_partials/tap-login-profile.mdx, docs/shadow/tap-update-old-guide.mdx
=> docs: Add usage instructions for the unionid scenario

docs/demos.mdx, docs/tap-download.mdx
=> Update Demo APK download link

docs/sdk/tapdb/sdk/client-side-integration.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/tapdb/sdk/client-side-integration.mdx
=> docs: update themis version

docs/sdk/tapdb/sdk/client-side-integration.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/tapdb/sdk/client-side-integration.mdx
=> fix: fix Themins version code

docs/sdk/start/quickstart.mdx
- 文档增加 iOS 未配置 Bundle ID 时出现的异常说明。
=> docs: ios unconfigured bundle id description

docs/sdk/_partials/tap-login-profile.mdx, docs/sdk/anti-addiction/faq.mdx, docs/sdk/anti-addiction/practice.mdx, docs/shadow/tap-update-old-guide.mdx, src/docComponents/MultiLang/index.tsx
=> docs: best practices for real-name authentication

docs/sdk/_partials/unity-sdk-installation.mdx, docs/sdk/anti-addiction/guide.mdx, docs/sdk/copyright-verification/guide.mdx, docs/sdk/embedded-moments/guide.mdx, docs/sdk/update/guide.mdx
=> 移除合规认证、唤起更新、内嵌动态的 LC 库依赖说明

README.md
=> docs: readme add nodejs version

docs/store/long-termops/long-term.mdx
=> docs:replacement of outdated image

docs/sdk/taptap-login/guide/start.mdx
- 内建账户方式增加需要绑定自定义 API 域名以及 SSL 证书管理说明。
=> docs: recommended login instruction

docs/sdk/taptap-login/features.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/taptap-login/features.mdx
=> docs: creating and replacing outdated images in the TapTap login profile document

docs/sdk/taptap-login/features.mdx, i18n/en/docusaurus-plugin-content-docs/current/sdk/taptap-login/features.mdx
=> docs: 更换 TapTap IO 登录简介中的过时图片

docusaurus.config.js, src/docComponents/MultiLang/index.tsx, versioned_docs/version-v4/sdk/_partials/languages.mdx, versioned_docs/version-v4/sdk/_partials/unity-sdk-installation.mdx, versioned_docs/version-v4/sdk/access/android-md5.mdx, versioned_docs/version-v4/sdk/access/quickstart.mdx, versioned_docs/version-v4/sdk/achievement/guide.mdx, versioned_docs/version-v4/sdk/anti-addiction/guide.mdx, versioned_docs/version-v4/sdk/anti-addiction/practice.mdx, versioned_docs/version-v4/sdk/copyright-verification/guide.mdx, versioned_docs/version-v4/sdk/embedded-moments/guide.mdx, versioned_docs/version-v4/sdk/tapdb/sdk/client-side-integration.mdx, versioned_docs/version-v4/sdk/taptap-login/guide.mdx, versioned_docs/version-v4/sdk/update/guide.mdx
- 修改代码样式高亮
- 添加 PC 登录说明
- 正版验证及更新唤起移除 iOS 平台
=> feat: update code style and remove unused platform

src/theme/Footer/TdsFooter/lib/ssr/footer.js
=> docs: footer organisation

cn/docs/sdk/access/quickstart.mdx
=> docs: Demonstration diagram of the supplemental signature configuration

cn/docs/sdk/tap-adn/tds-tapad.mdx, cn/docs/tap-download.mdx, cn/src/docComponents/v3SDKVersions.ts, cn/src/docComponents/v4SDKVersions.ts, cn/versioned_docs/version-v3/tap-download.mdx, hk/src/docComponents/v4SDKVersions.ts
feat:add game channel description
=> feat:update adn version from 3.16.3.34 ->  3.16.3.34_h1\n

cn/docs/sdk/copyright-verification/guide.mdx
- 更正正版验证 Android SDK 模块引入错误描述。
=> doc: correction of misdescription

cn/docs/sdk/taptap-appsafety/_category_.json, cn/docs/sdk/taptap-appsafety/guide.mdx
=> feature: add appsafety

cn/docs/sdk/taptap-appsafety/guide.mdx
=> doc: change pic

cn/docs/sdk/tds-gift/guide.mdx, cn/versioned_docs/version-v3/sdk/tds-gift/guide.mdx
=> docs: remove redundant code

cn/docs/sdk/update/guide.mdx, cn/versioned_docs/version-v3/sdk/update/guide.mdx
=> docs: add version verification for update module

cn/docs/sdk/achievement/_category_.json, cn/docs/sdk/apk-upload/_category_.json, cn/docs/sdk/embedded-moments/_category_.json, cn/docs/sdk/review/_category_.json, cn/docs/sdk/share/_category_.json, cn/docs/sdk/tap-adn/_category_.json, cn/docs/sdk/tap-iap/_category_.json, cn/docs/sdk/tap-play/_category_.json, cn/docs/sdk/tapdb/_category_.json, cn/docs/sdk/taplink/_category_.json, cn/docs/sdk/taptap-appsafety/_category_.json, cn/docs/sdk/tds-gift/_category_.json
=> docs: change module order
